version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: iotgo
    volumes:
      - mongo-volume:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017-27019:27017-27019"

volumes:
  mongo-volume: